HDL :=	ipcore_dir/bytefifo.vhd \
	ipcore_dir/rgbfifo.vhd \
	ipcore_dir/cdcfifo.vhd \
	ipcore_dir/image_selector_fifo.vhd \
	ipcore_dir/rgbfifo_synth.vhd \
	ipcore_dir/cmdfifo.vhd \
	ipcore_dir/edidram.vhd \
	ipcore_dir/cmdfifo_synth.vhd \
	ipcore_dir/rawUVCfifo.vhd \
	ipcore_dir/image_selector_fifo_synth.vhd \
	ipcore_dir/clkGen.vhd \
	ipcore_dir/bytefifo_synth.vhd \
	ipcore_dir/rawUVCfifo_synth.vhd \
	ipcore_dir/cdcfifo_synth.vhd \
	ipcore_dir/patternClk.vhd \
	ipcore_dir/ddr2ram/user_design/rtl/mcb_raw_wrapper.vhd \
	ipcore_dir/ddr2ram/user_design/rtl/mcb_soft_calibration_top.vhd \
	ipcore_dir/ddr2ram/user_design/rtl/mcb_soft_calibration.vhd \
	ipcore_dir/ddr2ram/user_design/rtl/iodrp_controller.vhd \
	ipcore_dir/ddr2ram/user_design/rtl/iodrp_mcb_controller.vhd \
	ipcore_dir/ddr2ram/user_design/rtl/ddr2ram.vhd \
	ipcore_dir/ddr2ram/user_design/rtl/memc3_wrapper.vhd \
	ipcore_dir/ddr2ram/user_design/rtl/memc3_infrastructure.vhd \
	ipcore_dir/ddr2ram/user_design/sim/rd_data_gen.vhd \
	ipcore_dir/ddr2ram/user_design/sim/memc3_tb_top.vhd \
	ipcore_dir/ddr2ram/user_design/sim/data_prbs_gen.vhd \
	ipcore_dir/ddr2ram/user_design/sim/sim_tb_top.vhd \
	ipcore_dir/ddr2ram/user_design/sim/tg_status.vhd \
	ipcore_dir/ddr2ram/user_design/sim/read_posted_fifo.vhd \
	ipcore_dir/ddr2ram/user_design/sim/read_data_path.vhd \
	ipcore_dir/ddr2ram/user_design/sim/write_data_path.vhd \
	ipcore_dir/ddr2ram/user_design/sim/mcb_traffic_gen.vhd \
	ipcore_dir/ddr2ram/user_design/sim/afifo.vhd \
	ipcore_dir/ddr2ram/user_design/sim/init_mem_pattern_ctr.vhd \
	ipcore_dir/ddr2ram/user_design/sim/cmd_gen.vhd \
	ipcore_dir/ddr2ram/user_design/sim/mcb_flow_control.vhd \
	ipcore_dir/ddr2ram/user_design/sim/wr_data_gen.vhd \
	ipcore_dir/ddr2ram/user_design/sim/sp6_data_gen.vhd \
	ipcore_dir/ddr2ram/user_design/sim/v6_data_gen.vhd \
	ipcore_dir/ddr2ram/user_design/sim/cmd_prbs_gen.vhd \
	ipcore_dir/bytefifoFPGA_synth.vhd \
	ipcore_dir/bytefifoFPGA.vhd \
	ipcore_dir/edidram_synth.vhd \
	hdl/hdmi2usb.vhd \
	hdl/jpeg_encoder/jpeg_encoder_top.vhd \
	hdl/jpeg_encoder/design/QUANTIZER.vhd \
	hdl/jpeg_encoder/design/DC_CR_ROM.vhd \
	hdl/jpeg_encoder/design/r_divider.vhd \
	hdl/jpeg_encoder/design/AC_CR_ROM.vhd \
	hdl/jpeg_encoder/design/MDCT_PKG.vhd \
	hdl/jpeg_encoder/design/SingleSM.vhd \
	hdl/jpeg_encoder/design/OutMux.vhd \
	hdl/jpeg_encoder/design/CtrlSM.vhd \
	hdl/jpeg_encoder/design/DoubleFifo.vhd \
	hdl/jpeg_encoder/design/DCT1D.vhd \
	hdl/jpeg_encoder/design/ROMR.vhd \
	hdl/jpeg_encoder/design/Huffman.vhd \
	hdl/jpeg_encoder/design/JPEG_PKG.vhd \
	hdl/jpeg_encoder/design/RleDoubleFifo.vhd \
	hdl/jpeg_encoder/design/HostIF.vhd \
	hdl/jpeg_encoder/design/AC_ROM.vhd \
	hdl/jpeg_encoder/design/ByteStuffer.vhd \
	hdl/jpeg_encoder/design/FIFO.vhd \
	hdl/jpeg_encoder/design/JpegEnc.vhd \
	hdl/jpeg_encoder/design/DC_ROM.vhd \
	hdl/jpeg_encoder/design/JFIFGen.vhd \
	hdl/jpeg_encoder/design/FDCT.vhd \
	hdl/jpeg_encoder/design/BUF_FIFO.vhd \
	hdl/usb/jpg_uvc.vhd \
	hdl/usb/cdc_in.vhd \
	hdl/usb/cdc_out.vhd \
	hdl/usb/usb_top.vhd \
	hdl/usb/raw_uvc.vhd \
	hdl/misc/pattern.vhd \
	hdl/misc/debouncer.vhd \
	hdl/misc/image_buffer.vhd \
	hdl/misc/rgb2ycbcr.vhd \
	hdl/misc/controller.vhd \
	hdl/misc/image_selector.vhd
